#!/usr/bin/env lua

require("os")

function run_yaourt(...)
    os.execute("yaourt " .. table.concat({...}," "))
end

function file_exists(name)
   local f=io.open(name,"r")
   if f~=nil then io.close(f) return true else return false end
end

local config_file_path = os.getenv("HOME") .. "/.yop"

if file_exists(config_file_path) then
    dofile(config_file_path)
end

if #arg == 0 then
    os.execute("yaourt")
else
    local all_args = table.concat(arg, " ")

    if arg[1]:sub(1, 1) == '-' then
        if #arg == 1 then
            run_yaourt(arg[1])
        else
            for i=2,#arg do
                run_yaourt(arg[1], arg[i])
            end
        end
    else
        run_yaourt(table.concat(arg," "))
    end
end
